spring:
  application:
    name: scs_cloudevents_sample
  cloud:
    function:
      definition: saveCustomer;logSavedCustomer
    stream:
      output-bindings: httpCustomer
      bindings:
        httpCustomer-out-0:
          destination: io.cloudevents.customer.commands
        saveCustomer-in-0:
          destination: io.cloudevents.customer.commands
          group: savers
        saveCustomer-out-0:
          destination: io.cloudevents.customer.events
        logSavedCustomer-in-0:
          destination: io.cloudevents.customer.events
          group: loggers